# Default values for elasticsearch-operator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: upmcenterprises/docker-elasticsearch-kubernetes
  tag: 6.1.3_0
  #pullSecret: test

clientReplicas: 3
masterReplicas: 2
dataReplicas: 3
dataVolumeSize: 1Gi
javaOpts: "-Xms512m -Xmx512m"


# Deploy data nodes across zones
#zones:
#  - us-east-1c
#  - us-east-1d
#  - us-east-1e

# Enable ssl or not
use-ssl: false

snapshot:
  enabled: false
  bucketName: elasticsnapshots
  schedule: "@every 2m"
  image: upmcenterprises/elasticsearch-cron:0.0.4
  authentication:
    enabled: false
    password: test
    username: test

storage:
# If class is set, then the other storage fields will not be used.
  class: standard
  type: standard
  # e.g. gp2 for AWS
  # e.g. kubernetes.io/aws-ebs for AWS
  classProvisioner: kubernetes.io/gce-pd
  # Retain or Delete
  reclaimPolicy: Delete

kibana:
  enabled: false
  image: docker.elastic.co/kibana/kibana-oss:6.1.3


cerebro:
  enabled: false
  image: upmcenterprises/cerebro:0.6.8

statsd:
  enabled: false
  host: ""

resources:
  requests:
    memory: 512Mi
    cpu: 100m
  limits:
    memory: 1024Mi
    cpu: 200m
