apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: well-behaved-logs
  name: well-behaved-logs
  namespace: default
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: well-behaved-logs
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: well-behaved-logs
    spec:
      containers:
      - image: calina/log-generator:1.0.3
        imagePullPolicy: Always
        name: behaved-logs
        ports:
          - name: http
            containerPort: 4003
            # protocol: TCP
        # readinessProbe:
        #   httpGet:
        #     path: /health
        #     port: http
        #   timeoutSeconds: 5
      restartPolicy: Always
